const CarDetails = [
    {
        carid: 1,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ-GMTzq43IZ-5PCiifwIavEUU3WkDhOF7zHw&usqp=CAU",
        name: "Toyota RAV4",
        year: 2021,
        capacity: 4,
        fuel: "Hybrid",
        distance: 6.1,
        type: "Automatic",
        price: 440,
        isLike: false,
    },
    {
        carid: 2,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSS2dslWp6POLJga0XVTFksjC5_WCzvcaKnKw&usqp=CAU",
        name: "BMW 3 Series",
        year: 2019,
        capacity: 4,
        fuel: "Gasoline",
        distance: 8.2,
        type: "Automatic",
        price: 350,
        isLike: false,
    },
    {
        carid: 3,
        image: "https://cdni.autocarindia.com/Utils/ImageResizer.ashx?n=https://cdni.autocarindia.com/ExtraImages/20190502023452_Volkswagen-T-Cross-white.jpg&w=700&q=90&c=1",
        name: "Volkswagen T-Cross",
        year: 2020,
        capacity: 4,
        fuel: "Gasoline",
        distance: 5.3,
        type: "Automatic",
        price: 400,
        isLike: false,
    },
    {
        carid: 4,
        image: "https://techcrunch.com/wp-content/uploads/2023/08/MY25_CADILLAC_ESCALADE_IQ_SPORT_B_GMCA2926_crop-3.jpg?w=730&crop=1",
        name: "Cadillac Escalade",
        year: 2020,
        capacity: 4,
        fuel: "Gasoline",
        distance: 7.7,
        type: "Automatic",
        price: 620,
        isLike: false,
    },
    {
        carid: 5,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQMB78DlDH6OWfQkqBN8TSyHm-DSHyGqEO8EqiU8pdpTgS_BVn1EHMNtC-0uwfo4KTWQk&usqp=CAU",
        name: "BMW 4 Series GTI",
        year: 2021,
        capacity: 4,
        fuel: "Gasoline",
        distance: 7.6,
        type: "Automatic",
        price: 530,
        isLike: false,
    },
    {
        carid: 6,
        image: "https://cdni.autocarindia.com/Utils/ImageResizer.ashx?n=https://cdni.autocarindia.com/Galleries/20200603102017_p90390170.jpg&w=730&h=484&q=75&c=1",
        name: "BMW 4 Series",
        year: 2019,
        capacity: 4,
        fuel: "Gasoline",
        distance: 7.2,
        type: "Automatic",
        price: 490,
        isLike: false,
    },
];

export default CarDetails;
